site_name: ESWC Workshop on Semantic Technology Implementation for Industrial Enterprises
site_description: Semantic Technology Implementation for Industrial Enterprises
theme:
  name: material
nav:
  - Home: index.md
docs_dir: markdown
site_dir: docs